server:
  port: 8080
  servlet:
    context-path: /redis

spring:
  redis:
    host: 120.25.159.230
    port: 6379
    database: 0
    password: "063018"
    timeout: 5000

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "063018"
    url: jdbc:mysql://120.25.159.230:3306/test?serverTimezone=GMT%2B8&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:   #连接池
      max-active: 20
      initial-size: 1
      min-idle: 3
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full